In [3]:
import pandas as pd

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df=pd.read_csv('covid_toy.csv')

In [5]:
df

    age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[100 rows x 6 columns]

In [6]:
df.head

<bound method NDFrame.head of     age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[100 rows x 6 columns]>

In [7]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop (columns=['has_covid']),df['has_covid'] ,test_size=0.2)
X_test

    age  gender  fever   cough       city
34   74    Male  102.0    Mild     Mumbai
92   82  Female  102.0  Strong    Kolkata
6    14    Male  101.0  Strong  Bangalore
19   42  Female    NaN  Strong  Bangalore
41   82    Male    NaN    Mild    Kolkata
52   47  Female  100.0  Strong  Bangalore
46   19  Female  101.0    Mild     Mumbai
72   83  Female  101.0    Mild    Kolkata
27   33  Female  102.0  Strong      Delhi
5    84  Female    NaN    Mild  Bangalore
94   79    Male    NaN  Strong    Kolkata
26   19  Female  100.0    Mild    Kolkata
16   69  Female  103.0    Mild    Kolkata
64   42    Male  104.0    Mild     Mumbai
81   65    Male   99.0    Mild      Delhi
91   38    Male    NaN    Mild      Delhi
95   12  Female  104.0    Mild  Bangalore
29   34  Female    NaN  Strong     Mumbai
93   27    Male  100.0    Mild    Kolkata
30   15    Male  101.0    Mild      Delhi

In [11]:
X_train

    age  gender  fever   cough       city
84   69  Female   98.0  Strong     Mumbai
36   38  Female  101.0    Mild  Bangalore
37   55    Male  100.0    Mild    Kolkata
13   64    Male  102.0    Mild  Bangalore
25   23    Male    NaN    Mild     Mumbai
..  ...     ...    ...     ...        ...
73   34    Male   98.0  Strong    Kolkata
15   70    Male  103.0  Strong    Kolkata
83   17  Female  104.0    Mild    Kolkata
87   47    Male  101.0  Strong  Bangalore
90   59  Female   99.0  Strong      Delhi

[80 rows x 5 columns]

In [13]:
from sklearn.compose import ColumnTransformer