In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df=pd.read_csv("train.txt",sep=';',header=None,names=['text','emotion'])

In [4]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [5]:
df.isnull().sum()

text       0
emotion    0
dtype: int64

Converting emotions colum to numeric

In [6]:
unique_emo=df['emotion'].unique()
emo_number={}
i=0
for emo in unique_emo:
    emo_number[emo]= i
    i+=1
df['emotion']=df['emotion'].map(emo_number)

In [7]:
df

                                                    text  emotion
0                                i didnt feel humiliated        0
1      i can go from feeling so hopeless to so damned...        0
2       im grabbing a minute to post i feel greedy wrong        1
3      i am ever feeling nostalgic about the fireplac...        2
4                                   i am feeling grouchy        1
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        0
15996  i am now turning and i feel pathetic that i am...        0
15997                     i feel strong and good overall        5
15998  i feel like this was such a rude comment and i...        1
15999  i know a lot but i feel so stupid because i ca...        0

[16000 rows x 2 columns]

Checking if text is lower or not

In [8]:
df['text']=df['text'].apply(lambda x:x.lower())

In [9]:
df

                                                    text  emotion
0                                i didnt feel humiliated        0
1      i can go from feeling so hopeless to so damned...        0
2       im grabbing a minute to post i feel greedy wrong        1
3      i am ever feeling nostalgic about the fireplac...        2
4                                   i am feeling grouchy        1
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        0
15996  i am now turning and i feel pathetic that i am...        0
15997                     i feel strong and good overall        5
15998  i feel like this was such a rude comment and i...        1
15999  i know a lot but i feel so stupid because i ca...        0

[16000 rows x 2 columns]

Remove Punctuation

In [10]:
import string
def remove_punc(txt):
    return txt.translate(str.maketrans('','',string.punctuation))

In [11]:
df['text']=df['text'].apply(remove_punc)

In [12]:
df

                                                    text  emotion
0                                i didnt feel humiliated        0
1      i can go from feeling so hopeless to so damned...        0
2       im grabbing a minute to post i feel greedy wrong        1
3      i am ever feeling nostalgic about the fireplac...        2
4                                   i am feeling grouchy        1
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        0
15996  i am now turning and i feel pathetic that i am...        0
15997                     i feel strong and good overall        5
15998  i feel like this was such a rude comment and i...        1
15999  i know a lot but i feel so stupid because i ca...        0

[16000 rows x 2 columns]

Remove Numbers

In [13]:
def remove_numbers(txt):
    new = ""
    for i in txt:
        if not i.isdigit():
            new = new + i
    return new

df['text'] = df['text'].apply(remove_numbers)

Remove URl

In [14]:
import re

def remove_urls(txt):
    return re.sub(r'https?://\S+|www\.\S+', '', txt)

df['text'] = df['text'].apply(remove_urls)

Remove Emojis

In [15]:
def remove_emoji(txt):
    new=""
    for i in txt:
        if i.isascii():
            new +=i
    return new
df['text'] = df['text'].apply(remove_emoji)

Remove Stopwards

In [16]:
%pip install nltk

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: nltk in C:\Users\hp\AppData\Roaming\Python\Python314\site-packages (3.10.2)
Requirement already satisfied: defusedxml in c:\Program Files\Python314\Lib\site-packages (from nltk) (0.7.1)
Requirement already satisfied: click in c:\Program Files\Python314\Lib\site-packages (from nltk) (8.3.2)
Requirement already satisfied: joblib in c:\Program Files\Python314\Lib\site-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in C:\Users\hp\AppData\Roaming\Python\Python314\site-packages (from nltk) (2026.7.19)
Requirement already satisfied: tqdm in C:\Users\hp\AppData\Roaming\Python\Python314\site-packages (from nltk) (4.70.0)
Requirement already satisfied: colorama in c:\Program Files\Python314\Lib\site-packages (from click->nltk) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [17]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [18]:
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\hp\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\hp\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [19]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\hp\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [20]:
stop_words=set(stopwords.words("english"))
len(stop_words)

198

In [21]:
df.loc[1],['text']

(text       i can go from feeling so hopeless to so damned...
 emotion                                                    0
 Name: 1, dtype: object,
 ['text'])

Tokenization

In [22]:
def remove(txt):
    words=word_tokenize(txt)
    cleaned=[]
    
    for i in words:
        if not i in stop_words:
            cleaned.append(i)
            
    return ' '.join(cleaned)

In [23]:
df['text'] = df['text'].apply(remove)

In [24]:
df.loc[1]['text']

'go feeling hopeless damned hopeful around someone cares awake'

In [25]:
df

                                                    text  emotion
0                                  didnt feel humiliated        0
1      go feeling hopeless damned hopeful around some...        0
2              im grabbing minute post feel greedy wrong        1
3      ever feeling nostalgic fireplace know still pr...        2
4                                        feeling grouchy        1
...                                                  ...      ...
15995      brief time beanbag said anna feel like beaten        0
15996  turning feel pathetic still waiting tables sub...        0
15997                           feel strong good overall        5
15998                     feel like rude comment im glad        1
15999                       know lot feel stupid portray        0

[16000 rows x 2 columns]

Bag of Words

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer